In [13]:
%load_ext autoreload
%autoreload 2

import sys
from pathlib import Path

project_root = Path.cwd().parent
sys.path.append(str(project_root))

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [14]:
import pickle

from src.text_processor import TextProcessor

with open("../data/parsed/text_blocks.pkl","rb") as f:
    text_blocks = pickle.load(f)

text_processor = TextProcessor()

text_documents = text_processor.process(text_blocks)

print(len(text_documents))

print(text_documents[0])

2125
page_content='low' metadata={'type': 'text', 'page': 2, 'label': 'text', 'window': 1}

In [15]:
with open("../data/parsed/text_documents.pkl", "wb") as f:
    pickle.dump(text_documents, f)

In [16]:
from src.table_processor import TableProcessor

with open("../data/parsed/table_blocks.pkl", "rb") as f:
    table_blocks = pickle.load(f)

processor = TableProcessor()

table_documents = processor.process(
    table_blocks,
    text_blocks,
)

with open("../data/parsed/table_documents.pkl", "wb") as f:
    pickle.dump(table_documents, f)

In [17]:
with open("../data/parsed/table_blocks.pkl","rb") as f:
    table_blocks = pickle.load(f)

In [18]:
table_processor = TableProcessor()

df = table_processor.table_to_dataframe(
    table_blocks[10]
)

df

(                             0          1          2             3          4  \
 0                                    2018       2018          2018       2017
 1        (Dollars in millions)  Net Sales  %of Total  Oper. Income  Net Sales
 2            Business Segments
 3                   Industrial   $ 12,267     37.4 %       $ 2,737   $ 11,866
 4          Safety and Graphics      6,827       20.8         1,720      6,235
 5                  Health Care      6,021       18.4         1,799      5,853
 6       Electronics and Energy      5,472       16.7         2,055      5,501
 7                     Consumer      4,796       14.6         1,027      4,731
 8    Corporate and Unallocated         50        0.2       (1,465)          3
 9   Elimination of Dual Credit    (2,668)      (8.1)         (666)    (2,532)
 10               Total Company   $ 32,765     100.0%       $ 7,207   $ 31,657

             5             6                     7                     8
 0        2017          2017  2018 vs 2017 %change  2018 vs 2017 %change
 1   %of Total  Oper. Income             Net Sales          Oper. Income
 2
 3      37.5 %       $ 2,490                 3.4 %                 9.9 %
 4        19.7         2,066                   9.5                (16.7)
 5        18.5         1,764                   2.9                   2.0
 6        17.4         1,377                 (0.5)                  49.3
 7        14.9         1,004                   1.4                   2.4
 8           -         (395)                     -                     -
 9       (8.0)         (614)                     -                     -
 10    100.0 %       $ 7,692                 3.5 %                (6.3)%  ,
 [[False, True, True, True, True, True, True, True, True],
  [False, True, True, True, True, True, True, True, True],
  [False, False, False, False, False, False, False, False, False],
  [False, False, False, False, False, False, False, False, False],
  [False, False, False, False, False, False, False, False, False],
  [False, False, False, False, False, False, False, False, False],
  [False, False, False, False, False, False, False, False, False],
  [False, False, False, False, False, False, False, False, False],
  [False, False, False, False, False, False, False, False, False],
  [False, False, False, False, False, False, False, False, False],
  [False, False, False, False, False, False, False, False, False]])

In [19]:
print(type(table_blocks))
print(len(table_blocks))
print(type(table_blocks[0]))
print(table_blocks[0])

<class 'list'>
116
<class 'docling_core.types.doc.document.TableItem'>

In [20]:
for i in range(5):

    print("=" * 80)
    print("Table", i)

    df, mask = table_processor.table_to_dataframe(
        table_blocks[i]
    )

    df = table_processor.merge_headers(df, mask)

    display(df.head())

================================================================================
Table 0

                                      Beginning Page
0   PART I
1   ITEM 1                   Business              4
2  ITEM 1A               Risk Factors             10
3  ITEM 1B  Unresolved Staff Comments             12
4   ITEM 2                 Properties             12

================================================================================
Table 1

                                                             Beginning Page
0  ITEM 8  Financial Statements and Supplementary Data (c...
1          Consolidated Statement of Changes in Equity fo...             59
2          Consolidated Statement of Cash Flows for the y...             60
3                 Notes to Consolidated Financial Statements             61
4                    Note 1. Significant Accounting Policies             61

================================================================================
Table 2

,Name,Age,Present Position,Year Elected to Present Position,Other Positions Held During 2014-2018
0,Inge. G. Thulin,65,Executive Chairman of the Board,2018,"Chairman of the Board, President and Chief Exe..."
1,Michael F. Roman,59,Chief Executive Officer,2018,Chief Operating Officer and Executive Vice Pre...
2,John P. Banovetz,51,"Senior Vice President, Research and Developmen...",2017,"Managing Director, DACH Region, 2016-2017 Vice..."
3,James L. Bauman,59,"Executive Vice President, Industrial Business ...",2017,"Executive Vice President, Electronics and Ener..."
4,Julie L. Bushman,57,"Executive Vice President, International Operat...",2017,"Senior Vice President, Business Transformation..."

================================================================================
Table 3

,Name,Age,Present Position,Year Elected to Present Position,Other Positions Held During 2014-2018
0,Jon T. Lindekugel,54,"Senior Vice President, Manufacturing and Suppl...",2018,"Senior Vice President, Supply Chain, 2017 Seni..."
1,Kristen M. Ludgate,56,"Senior Vice President, Human Resources",2018,"Senior Vice President, Corporate Communication..."
2,Mojdeh Poul,55,"Executive Vice President, Safety and Graphics ...",2018,"President and General Manager, 3M Canada, 2016..."
3,Michael G. Vale,52,"Executive Vice President, Health Care Business...",2016,"Executive Vice President, Consumer Business Gr..."

================================================================================
Table 4

,Period,Total Number of Shares Purchased (1),Average Price Paid per Share,Total Number of Shares Purchased as Part of Publicly Announced Plans or Programs (2),Maximum Approximate Dollar Value of Shares that May Yet Be Purchased under the Plans or Programs (Millions)
0,"January 1-31, 2018","714,575",$ 245.98,"714,138","$ 4,894"
1,"February 1-28, 2018","1,420,634",$ 233.78,"1,420,599","$ 4,562"
2,"March 1-31, 2018","1,791,496",$ 228.82,"1,791,496","$ 4,152"
3,"Total January 1-March 31, 2018","3,926,705",$ 233.74,"3,926,233","$ 4,152"
4,"April 1-30, 2018","2,135,968",$ 213.63,"2,135,968","$ 3,696"

In [21]:
df, mask = table_processor.table_to_dataframe(table_blocks[0])

df = table_processor.merge_headers(df, mask)

print(df.shape)

(29, 3)

In [22]:
for i, table in enumerate(table_blocks):
    rows = table.data.num_rows
    cols = table.data.num_cols

    if rows > 10 and cols > 4:
        print(i, rows, cols)

2 12 5
4 18 5
5 12 6
8 11 9
10 11 9
12 23 7
13 24 7
14 24 7
39 43 7
46 19 5
59 24 5
60 18 5
69 39 6
73 26 7
77 24 10
81 35 9
82 32 9
83 34 9
84 15 6
85 12 5
88 14 6
89 14 6
92 17 5
93 19 5
98 11 7

In [29]:
df = table_processor.table_to_dataframe(table_blocks[46])
display(df)

,0,1,2,3,4
0,,2017 Acquisition Activity,2017 Acquisition Activity,2017 Acquisition Activity,2017 Acquisition Activity
1,(Millions) Asset (Liability),Scott Safety,Other,Total,Finite-Lived Intangible-Asset Weighted-Average...
2,Accounts receivable,$ 100,$ -,$ 100,
3,Inventory,79,-,79,
4,Other current assets,10,-,10,
5,"Property, plant, and equipment",74,-,74,
6,Purchased finite-lived intangible assets:,,,,
7,Customer related intangible assets,439,3,442,15
8,Other technology-based intangible assets,125,2,127,10
9,Definite-lived tradenames,285,-,285,17
10,Other amortizable intangible assets,-,1,1,5
11,Purchased goodwill,"1,296",6,"1,302",
12,Accounts payable and other liabilities,(100),-,(100),
13,Deferred tax asset/(liability),(297),-,(297),
14,Net assets acquired,"$ 2,011",$ 12,"$ 2,023",
15,Supplemental information:,,,,
16,Cash paid,"$ 2,020",$ 12,"$ 2,032",
17,Less: Cash acquired,9,-,9,
18,"Cash paid, net of cash acquired","$ 2,011",$ 12,"$ 2,023",

In [23]:
for cell in table_blocks[46].data.table_cells:
    if cell.column_header:
        print(
            cell.text,
            cell.start_row_offset_idx,
            cell.start_col_offset_idx
        )

2017 Acquisition Activity 0 1
Finite-Lived Intangible-Asset Weighted-Average Lives (Years) 1 4
Scott Safety 1 1
Other 1 2
Total 1 3

In [24]:
count = 0

for block in text_blocks:
    if len(block.text.strip()) < 40:
        count += 1

print(count)

736